EESchema Schematic File Version 4
EELAYER 30 0
EELAYER END
$Descr USLetter 8500 11000 portrait
encoding utf-8
Sheet 3 5
Title "DDR4 signals on the DIMM. (288 pins, ECC)."
Date "2019-11-01"
Rev "1"
Comp ""
Comment1 "Autogenerated. See misc/check-ddr4.py"
Comment2 ""
Comment3 ""
Comment4 ""
$EndDescr
$Comp
L ddr4:DDR4_connector J?
U 1 1 5DBA2BA4
P 4450 4250
AR Path="/5DBA2BA4" Ref="J?"  Part="1" 
AR Path="/5DB9ED49/5DBA2BA4" Ref="J2"  Part="1" 
F 0 "J2" H 4450 4797 50  0000 C CNB
F 1 "DDR4_to_DIMM" H 4450 3987 50  0000 C CNN
F 2 "fi-library:ddr4-edge-conn-female" H 4450 4250 50  0001 C CNN
F 3 "" H 4450 4250 50  0001 C CNN
	1    4450 4250
	1    0    0    -1  
$EndComp
Text GLabel 2250 700  0    50   Input ~ 0
NC_DIMM
Text GLabel 2250 800  0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 900  0    50   Input ~ 0
DQ4_DIMM
Text GLabel 2250 1000 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 1100 0    50   Input ~ 0
DQ0_DIMM
Text GLabel 2250 1200 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 1300 0    50   Input ~ 0
DQS9_t_TDQS9_t_DIMM
Text GLabel 2250 1400 0    50   Input ~ 0
DQS09_c_TDQS9_c_DIMM
Text GLabel 2250 1500 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 1600 0    50   Input ~ 0
DQ6_DIMM
Text GLabel 2250 1700 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 1800 0    50   Input ~ 0
DQ2_DIMM
Text GLabel 2250 1900 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 2000 0    50   Input ~ 0
DQ12_DIMM
Text GLabel 2250 2100 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 2200 0    50   Input ~ 0
DQ8_DIMM
Text GLabel 2250 2300 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 2400 0    50   Input ~ 0
DQS10_t_TDQS10_t_DIMM
Text GLabel 2250 2500 0    50   Input ~ 0
DQS10_c_TDQS10_c_DIMM
Text GLabel 2250 2600 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 2700 0    50   Input ~ 0
DQ14_DIMM
Text GLabel 2250 2800 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 2900 0    50   Input ~ 0
DQ10_DIMM
Text GLabel 2250 3000 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 3100 0    50   Input ~ 0
DQ20_DIMM
Text GLabel 2250 3200 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 3300 0    50   Input ~ 0
DQ16_DIMM
Text GLabel 2250 3400 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 3500 0    50   Input ~ 0
DQS11_t_TDQS11_t_DIMM
Text GLabel 2250 3600 0    50   Input ~ 0
DQS11_c_TDQS11_c_DIMM
Text GLabel 2250 3700 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 3800 0    50   Input ~ 0
DQ22_DIMM
Text GLabel 2250 3900 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 4000 0    50   Input ~ 0
DQ18_DIMM
Text GLabel 2250 4100 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 4200 0    50   Input ~ 0
DQ28_DIMM
Text GLabel 2250 4300 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 4400 0    50   Input ~ 0
DQ24_DIMM
Text GLabel 2250 4500 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 4600 0    50   Input ~ 0
DQS12_t_TDQS12_t_DIMM
Text GLabel 2250 4700 0    50   Input ~ 0
DQS12_c_TDQS12_c_DIMM
Text GLabel 2250 4800 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 4900 0    50   Input ~ 0
DQ30_DIMM
Text GLabel 2250 5000 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 5100 0    50   Input ~ 0
DQ26_DIMM
Text GLabel 2250 5200 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 5300 0    50   Input ~ 0
CB4_DIMM
Text GLabel 2250 5400 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 5500 0    50   Input ~ 0
CB0_DIMM
Text GLabel 2250 5600 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 5700 0    50   Input ~ 0
DQS17_t_TDQS17_t_DIMM
Text GLabel 2250 5800 0    50   Input ~ 0
DQS17_c_TDQS17_c_DIMM
Text GLabel 2250 5900 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 6000 0    50   Input ~ 0
CB6_DIMM
Text GLabel 2250 6100 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 6200 0    50   Input ~ 0
CB2_DIMM
Text GLabel 2250 6300 0    50   Input ~ 0
VSS_DIMM
Text GLabel 2250 6400 0    50   Input ~ 0
RESET_n_DIMM
Text GLabel 2250 6500 0    50   Input ~ 0
VDD_DIMM
Text GLabel 2250 6600 0    50   Input ~ 0
CKE0_DIMM
Text GLabel 2250 6700 0    50   Input ~ 0
VDD_DIMM
Text GLabel 2250 6800 0    50   Input ~ 0
ACT_n_DIMM
Text GLabel 2250 6900 0    50   Input ~ 0
BG0_DIMM
Text GLabel 2250 7000 0    50   Input ~ 0
VDD_DIMM
Text GLabel 2250 7100 0    50   Input ~ 0
A12_BC_n_DIMM
Text GLabel 2250 7200 0    50   Input ~ 0
A9_DIMM
Text GLabel 2250 7300 0    50   Input ~ 0
VDD_DIMM
Text GLabel 2250 7400 0    50   Input ~ 0
A8_DIMM
Text GLabel 2250 7500 0    50   Input ~ 0
A6_DIMM
Text GLabel 2250 7600 0    50   Input ~ 0
VDD_DIMM
Text GLabel 2250 7700 0    50   Input ~ 0
A3_DIMM
Text GLabel 2250 7800 0    50   Input ~ 0
A1_DIMM
Text GLabel 3650 700  2    50   Input ~ 0
VDD_DIMM
Text GLabel 3650 800  2    50   Input ~ 0
CK0_t_DIMM
Text GLabel 3650 900  2    50   Input ~ 0
CK0_c_DIMM
Text GLabel 3650 1000 2    50   Input ~ 0
VDD_DIMM
Text GLabel 3650 1100 2    50   Input ~ 0
VTT_DIMM
Text GLabel 3650 1200 2    50   Input ~ 0
EVENT_n_DIMM
Text GLabel 3650 1300 2    50   Input ~ 0
A0_DIMM
Text GLabel 3650 1400 2    50   Input ~ 0
VDD_DIMM
Text GLabel 3650 1500 2    50   Input ~ 0
BA0_DIMM
Text GLabel 3650 1600 2    50   Input ~ 0
RAS_n_A16_DIMM
Text GLabel 3650 1700 2    50   Input ~ 0
VDD_DIMM
Text GLabel 3650 1800 2    50   Input ~ 0
CS0_n_DIMM
Text GLabel 3650 1900 2    50   Input ~ 0
VDD_DIMM
Text GLabel 3650 2000 2    50   Input ~ 0
CAS_n_A15_DIMM
Text GLabel 3650 2100 2    50   Input ~ 0
ODT0_DIMM
Text GLabel 3650 2200 2    50   Input ~ 0
VDD_DIMM
Text GLabel 3650 2300 2    50   Input ~ 0
CS1_n_NC_DIMM
Text GLabel 3650 2400 2    50   Input ~ 0
VDD_DIMM
Text GLabel 3650 2500 2    50   Input ~ 0
ODT1_NC_DIMM
Text GLabel 3650 2600 2    50   Input ~ 0
VDD_DIMM
Text GLabel 3650 2700 2    50   Input ~ 0
CS2_n_C0_DIMM
Text GLabel 3650 2800 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 2900 2    50   Input ~ 0
DQ36_DIMM
Text GLabel 3650 3000 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 3100 2    50   Input ~ 0
DQ32_DIMM
Text GLabel 3650 3200 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 3300 2    50   Input ~ 0
DQS13_t_TDQ13_t_DIMM
Text GLabel 3650 3400 2    50   Input ~ 0
DQS13_c_TDQS13_c_DIMM
Text GLabel 3650 3500 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 3600 2    50   Input ~ 0
DQ38_DIMM
Text GLabel 3650 3700 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 3800 2    50   Input ~ 0
DQ34_DIMM
Text GLabel 3650 3900 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 4000 2    50   Input ~ 0
DQ44_DIMM
Text GLabel 3650 4100 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 4200 2    50   Input ~ 0
DQ40_DIMM
Text GLabel 3650 4300 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 4400 2    50   Input ~ 0
DQS14_t_TDQS14_t_DIMM
Text GLabel 3650 4500 2    50   Input ~ 0
DQS14_c_TDQS14_c_DIMM
Text GLabel 3650 4600 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 4700 2    50   Input ~ 0
DQ46_DIMM
Text GLabel 3650 4800 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 4900 2    50   Input ~ 0
DQ42_DIMM
Text GLabel 3650 5000 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 5100 2    50   Input ~ 0
DQ52_DIMM
Text GLabel 3650 5200 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 5300 2    50   Input ~ 0
DQ48_DIMM
Text GLabel 3650 5400 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 5500 2    50   Input ~ 0
DQS15_t_TDQS15_t_DIMM
Text GLabel 3650 5600 2    50   Input ~ 0
DQS15_c_TDQS15_c_DIMM
Text GLabel 3650 5700 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 5800 2    50   Input ~ 0
DQ54_DIMM
Text GLabel 3650 5900 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 6000 2    50   Input ~ 0
DQ50_DIMM
Text GLabel 3650 6100 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 6200 2    50   Input ~ 0
DQ60_DIMM
Text GLabel 3650 6300 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 6400 2    50   Input ~ 0
DQ56_DIMM
Text GLabel 3650 6500 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 6600 2    50   Input ~ 0
DQS16_t_TDQS16_t_DIMM
Text GLabel 3650 6700 2    50   Input ~ 0
DQS16_c_TDQS16_c_DIMM
Text GLabel 3650 6800 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 6900 2    50   Input ~ 0
DQ62_DIMM
Text GLabel 3650 7000 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 7100 2    50   Input ~ 0
DQ58_DIMM
Text GLabel 3650 7200 2    50   Input ~ 0
VSS_DIMM
Text GLabel 3650 7300 2    50   Input ~ 0
SA0_DIMM
Text GLabel 3650 7400 2    50   Input ~ 0
SA1_DIMM
Text GLabel 3650 7500 2    50   Input ~ 0
SCL_DIMM
Text GLabel 3650 7600 2    50   Input ~ 0
VPP_DIMM
Text GLabel 3650 7700 2    50   Input ~ 0
VPP_DIMM
Text GLabel 3650 7800 2    50   Input ~ 0
NC_DIMM
Text GLabel 5250 700  0    50   Input ~ 0
NC_DIMM
Text GLabel 5250 800  0    50   Input ~ 0
VREFCA_DIMM
Text GLabel 5250 900  0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 1000 0    50   Input ~ 0
DQ5_DIMM
Text GLabel 5250 1100 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 1200 0    50   Input ~ 0
DQ1_DIMM
Text GLabel 5250 1300 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 1400 0    50   Input ~ 0
DQS0_c_DIMM
Text GLabel 5250 1500 0    50   Input ~ 0
DQS0_t_DIMM
Text GLabel 5250 1600 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 1700 0    50   Input ~ 0
DQ7_DIMM
Text GLabel 5250 1800 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 1900 0    50   Input ~ 0
DQ3_DIMM
Text GLabel 5250 2000 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 2100 0    50   Input ~ 0
DQ13_DIMM
Text GLabel 5250 2200 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 2300 0    50   Input ~ 0
DQ9_DIMM
Text GLabel 5250 2400 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 2500 0    50   Input ~ 0
DQS1_c_DIMM
Text GLabel 5250 2600 0    50   Input ~ 0
DQS1_t_DIMM
Text GLabel 5250 2700 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 2800 0    50   Input ~ 0
DQ15_DIMM
Text GLabel 5250 2900 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 3000 0    50   Input ~ 0
DQ11_DIMM
Text GLabel 5250 3100 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 3200 0    50   Input ~ 0
DQ21_DIMM
Text GLabel 5250 3300 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 3400 0    50   Input ~ 0
DQ17_DIMM
Text GLabel 5250 3500 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 3600 0    50   Input ~ 0
DQS2_c_DIMM
Text GLabel 5250 3700 0    50   Input ~ 0
DQS2_t_DIMM
Text GLabel 5250 3800 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 3900 0    50   Input ~ 0
DQ23_DIMM
Text GLabel 5250 4000 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 4100 0    50   Input ~ 0
DQ19_DIMM
Text GLabel 5250 4200 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 4300 0    50   Input ~ 0
DQ29_DIMM
Text GLabel 5250 4400 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 4500 0    50   Input ~ 0
DQ25_DIMM
Text GLabel 5250 4600 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 4700 0    50   Input ~ 0
DQS3_c_DIMM
Text GLabel 5250 4800 0    50   Input ~ 0
DQS3_t_DIMM
Text GLabel 5250 4900 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 5000 0    50   Input ~ 0
DQ31_DIMM
Text GLabel 5250 5100 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 5200 0    50   Input ~ 0
DQ27_DIMM
Text GLabel 5250 5300 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 5400 0    50   Input ~ 0
CB5_DIMM
Text GLabel 5250 5500 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 5600 0    50   Input ~ 0
CB1_DIMM
Text GLabel 5250 5700 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 5800 0    50   Input ~ 0
DQS8_c_DIMM
Text GLabel 5250 5900 0    50   Input ~ 0
DQS8_t_DIMM
Text GLabel 5250 6000 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 6100 0    50   Input ~ 0
CB7_DIMM
Text GLabel 5250 6200 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 6300 0    50   Input ~ 0
CB3_DIMM
Text GLabel 5250 6400 0    50   Input ~ 0
VSS_DIMM
Text GLabel 5250 6500 0    50   Input ~ 0
CKE1_NC_DIMM
Text GLabel 5250 6600 0    50   Input ~ 0
VDD_DIMM
Text GLabel 5250 6700 0    50   Input ~ 0
NC_DIMM
Text GLabel 5250 6800 0    50   Input ~ 0
VDD_DIMM
Text GLabel 5250 6900 0    50   Input ~ 0
BG1_DIMM
Text GLabel 5250 7000 0    50   Input ~ 0
ALERT_n_DIMM
Text GLabel 5250 7100 0    50   Input ~ 0
VDD_DIMM
Text GLabel 5250 7200 0    50   Input ~ 0
A11_DIMM
Text GLabel 5250 7300 0    50   Input ~ 0
A7_DIMM
Text GLabel 5250 7400 0    50   Input ~ 0
VDD_DIMM
Text GLabel 5250 7500 0    50   Input ~ 0
A5_DIMM
Text GLabel 5250 7600 0    50   Input ~ 0
A4_DIMM
Text GLabel 5250 7700 0    50   Input ~ 0
VDD_DIMM
Text GLabel 5250 7800 0    50   Input ~ 0
A2_DIMM
Text GLabel 6650 700  2    50   Input ~ 0
VDD_DIMM
Text GLabel 6650 800  2    50   Input ~ 0
CK1_t_DIMM
Text GLabel 6650 900  2    50   Input ~ 0
CK1_c_DIMM
Text GLabel 6650 1000 2    50   Input ~ 0
VDD_DIMM
Text GLabel 6650 1100 2    50   Input ~ 0
VTT_DIMM
Text GLabel 6650 1200 2    50   Input ~ 0
PARITY_DIMM
Text GLabel 6650 1300 2    50   Input ~ 0
VDD_DIMM
Text GLabel 6650 1400 2    50   Input ~ 0
BA1_DIMM
Text GLabel 6650 1500 2    50   Input ~ 0
A10_AP_DIMM
Text GLabel 6650 1600 2    50   Input ~ 0
VDD_DIMM
Text GLabel 6650 1700 2    50   Input ~ 0
NC_DIMM
Text GLabel 6650 1800 2    50   Input ~ 0
WE_n_A14_DIMM
Text GLabel 6650 1900 2    50   Input ~ 0
VDD_DIMM
Text GLabel 6650 2000 2    50   Input ~ 0
NC_DIMM
Text GLabel 6650 2100 2    50   Input ~ 0
VDD_DIMM
Text GLabel 6650 2200 2    50   Input ~ 0
A13_DIMM
Text GLabel 6650 2300 2    50   Input ~ 0
VDD_DIMM
Text GLabel 6650 2400 2    50   Input ~ 0
A17_DIMM
Text GLabel 6650 2500 2    50   Input ~ 0
NC_C2_DIMM
Text GLabel 6650 2600 2    50   Input ~ 0
VDD_DIMM
Text GLabel 6650 2700 2    50   Input ~ 0
CS3_n_C1,NC_DIMM
Text GLabel 6650 2800 2    50   Input ~ 0
SA2_DIMM
Text GLabel 6650 2900 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 3000 2    50   Input ~ 0
DQ37_DIMM
Text GLabel 6650 3100 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 3200 2    50   Input ~ 0
DQ33_DIMM
Text GLabel 6650 3300 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 3400 2    50   Input ~ 0
DQS4_c_DIMM
Text GLabel 6650 3500 2    50   Input ~ 0
DQS4_t_DIMM
Text GLabel 6650 3600 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 3700 2    50   Input ~ 0
DQ39_DIMM
Text GLabel 6650 3800 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 3900 2    50   Input ~ 0
DQ35_DIMM
Text GLabel 6650 4000 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 4100 2    50   Input ~ 0
DQ45_DIMM
Text GLabel 6650 4200 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 4300 2    50   Input ~ 0
DQ41_DIMM
Text GLabel 6650 4400 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 4500 2    50   Input ~ 0
DQS5_c_DIMM
Text GLabel 6650 4600 2    50   Input ~ 0
DQS5_t_DIMM
Text GLabel 6650 4700 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 4800 2    50   Input ~ 0
DQ47_DIMM
Text GLabel 6650 4900 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 5000 2    50   Input ~ 0
DQ43_DIMM
Text GLabel 6650 5100 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 5200 2    50   Input ~ 0
DQ53_DIMM
Text GLabel 6650 5300 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 5400 2    50   Input ~ 0
DQ49_DIMM
Text GLabel 6650 5500 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 5600 2    50   Input ~ 0
DQS6_c_DIMM
Text GLabel 6650 5700 2    50   Input ~ 0
DQS6_t_DIMM
Text GLabel 6650 5800 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 5900 2    50   Input ~ 0
DQ55_DIMM
Text GLabel 6650 6000 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 6100 2    50   Input ~ 0
DQ51_DIMM
Text GLabel 6650 6200 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 6300 2    50   Input ~ 0
DQ61_DIMM
Text GLabel 6650 6400 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 6500 2    50   Input ~ 0
DQ57_DIMM
Text GLabel 6650 6600 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 6700 2    50   Input ~ 0
DQS7_c_DIMM
Text GLabel 6650 6800 2    50   Input ~ 0
DQS7_t_DIMM
Text GLabel 6650 6900 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 7000 2    50   Input ~ 0
DQ63_DIMM
Text GLabel 6650 7100 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 7200 2    50   Input ~ 0
DQ59_DIMM
Text GLabel 6650 7300 2    50   Input ~ 0
VSS_DIMM
Text GLabel 6650 7400 2    50   Input ~ 0
VDDSPD_DIMM
Text GLabel 6650 7500 2    50   Input ~ 0
SDA_DIMM
Text GLabel 6650 7600 2    50   Input ~ 0
VPP_DIMM
Text GLabel 6650 7700 2    50   Input ~ 0
VPP_DIMM
Text GLabel 6650 7800 2    50   Input ~ 0
VPP_DIMM
$EndSCHEMATC
