EESchema Schematic File Version 4
EELAYER 30 0
EELAYER END
$Descr USLetter 8500 11000 portrait
encoding utf-8
Sheet 2 5
Title "The 228 DDR signals of the connector on the Mother Board"
Date "2019-11-01"
Rev "1"
Comp ""
Comment1 "Autogenerated. See misc/check-ddr4.py"
Comment2 ""
Comment3 ""
Comment4 ""
$EndDescr
$Comp
L ddr4:DDR4_connector J?
U 1 1 5DB9E512
P 4350 4400
AR Path="/5DB9E512" Ref="J?"  Part="1" 
AR Path="/5DB9A55F/5DB9E512" Ref="J1"  Part="1" 
F 0 "J1" H 4350 4947 50  0000 C CNB
F 1 "DDR4_to_MB" H 4350 4000 50  0000 C CNN
F 2 "fi-library:ddr4-edge-conn-male" H 4350 4400 50  0001 C CNN
F 3 "" H 4350 4400 50  0001 C CNN
	1    4350 4400
	1    0    0    -1  
$EndComp
Text GLabel 2150 850  0    50   Input ~ 0
NC_MB
Text GLabel 2150 950  0    50   Input ~ 0
VSS_MB
Text GLabel 2150 1050 0    50   Input ~ 0
DQ4_MB
Text GLabel 2150 1150 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 1250 0    50   Input ~ 0
DQ0_MB
Text GLabel 2150 1350 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 1450 0    50   Input ~ 0
DQS9_t_TDQS9_t_MB
Text GLabel 2150 1550 0    50   Input ~ 0
DQS09_c_TDQS9_c_MB
Text GLabel 2150 1650 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 1750 0    50   Input ~ 0
DQ6_MB
Text GLabel 2150 1850 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 1950 0    50   Input ~ 0
DQ2_MB
Text GLabel 2150 2050 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 2150 0    50   Input ~ 0
DQ12_MB
Text GLabel 2150 2250 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 2350 0    50   Input ~ 0
DQ8_MB
Text GLabel 2150 2450 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 2550 0    50   Input ~ 0
DQS10_t_TDQS10_t_MB
Text GLabel 2150 2650 0    50   Input ~ 0
DQS10_c_TDQS10_c_MB
Text GLabel 2150 2750 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 2850 0    50   Input ~ 0
DQ14_MB
Text GLabel 2150 2950 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 3050 0    50   Input ~ 0
DQ10_MB
Text GLabel 2150 3150 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 3250 0    50   Input ~ 0
DQ20_MB
Text GLabel 2150 3350 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 3450 0    50   Input ~ 0
DQ16_MB
Text GLabel 2150 3550 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 3650 0    50   Input ~ 0
DQS11_t_TDQS11_t_MB
Text GLabel 2150 3750 0    50   Input ~ 0
DQS11_c_TDQS11_c_MB
Text GLabel 2150 3850 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 3950 0    50   Input ~ 0
DQ22_MB
Text GLabel 2150 4050 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 4150 0    50   Input ~ 0
DQ18_MB
Text GLabel 2150 4250 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 4350 0    50   Input ~ 0
DQ28_MB
Text GLabel 2150 4450 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 4550 0    50   Input ~ 0
DQ24_MB
Text GLabel 2150 4650 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 4750 0    50   Input ~ 0
DQS12_t_TDQS12_t_MB
Text GLabel 2150 4850 0    50   Input ~ 0
DQS12_c_TDQS12_c_MB
Text GLabel 2150 4950 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 5050 0    50   Input ~ 0
DQ30_MB
Text GLabel 2150 5150 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 5250 0    50   Input ~ 0
DQ26_MB
Text GLabel 2150 5350 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 5450 0    50   Input ~ 0
CB4_MB
Text GLabel 2150 5550 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 5650 0    50   Input ~ 0
CB0_MB
Text GLabel 2150 5750 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 5850 0    50   Input ~ 0
DQS17_t_TDQS17_t_MB
Text GLabel 2150 5950 0    50   Input ~ 0
DQS17_c_TDQS17_c_MB
Text GLabel 2150 6050 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 6150 0    50   Input ~ 0
CB6_MB
Text GLabel 2150 6250 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 6350 0    50   Input ~ 0
CB2_MB
Text GLabel 2150 6450 0    50   Input ~ 0
VSS_MB
Text GLabel 2150 6550 0    50   Input ~ 0
RESET_n_MB
Text GLabel 2150 6650 0    50   Input ~ 0
VDD_MB
Text GLabel 2150 6750 0    50   Input ~ 0
CKE0_MB
Text GLabel 2150 6850 0    50   Input ~ 0
VDD_MB
Text GLabel 2150 6950 0    50   Input ~ 0
ACT_n_MB
Text GLabel 2150 7050 0    50   Input ~ 0
BG0_MB
Text GLabel 2150 7150 0    50   Input ~ 0
VDD_MB
Text GLabel 2150 7250 0    50   Input ~ 0
A12_BC_n_MB
Text GLabel 2150 7350 0    50   Input ~ 0
A9_MB
Text GLabel 2150 7450 0    50   Input ~ 0
VDD_MB
Text GLabel 2150 7550 0    50   Input ~ 0
A8_MB
Text GLabel 2150 7650 0    50   Input ~ 0
A6_MB
Text GLabel 2150 7750 0    50   Input ~ 0
VDD_MB
Text GLabel 2150 7850 0    50   Input ~ 0
A3_MB
Text GLabel 2150 7950 0    50   Input ~ 0
A1_MB
Text GLabel 3550 850  2    50   Input ~ 0
VDD_MB
Text GLabel 3550 950  2    50   Input ~ 0
CK0_t_MB
Text GLabel 3550 1050 2    50   Input ~ 0
CK0_c_MB
Text GLabel 3550 1150 2    50   Input ~ 0
VDD_MB
Text GLabel 3550 1250 2    50   Input ~ 0
VTT_MB
Text GLabel 3550 1350 2    50   Input ~ 0
EVENT_n_MB
Text GLabel 3550 1450 2    50   Input ~ 0
A0_MB
Text GLabel 3550 1550 2    50   Input ~ 0
VDD_MB
Text GLabel 3550 1650 2    50   Input ~ 0
BA0_MB
Text GLabel 3550 1750 2    50   Input ~ 0
RAS_n_A16_MB
Text GLabel 3550 1850 2    50   Input ~ 0
VDD_MB
Text GLabel 3550 1950 2    50   Input ~ 0
CS0_n_MB
Text GLabel 3550 2050 2    50   Input ~ 0
VDD_MB
Text GLabel 3550 2150 2    50   Input ~ 0
CAS_n_A15_MB
Text GLabel 3550 2250 2    50   Input ~ 0
ODT0_MB
Text GLabel 3550 2350 2    50   Input ~ 0
VDD_MB
Text GLabel 3550 2450 2    50   Input ~ 0
CS1_n_NC_MB
Text GLabel 3550 2550 2    50   Input ~ 0
VDD_MB
Text GLabel 3550 2650 2    50   Input ~ 0
ODT1_NC_MB
Text GLabel 3550 2750 2    50   Input ~ 0
VDD_MB
Text GLabel 3550 2850 2    50   Input ~ 0
CS2_n_C0_MB
Text GLabel 3550 2950 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 3050 2    50   Input ~ 0
DQ36_MB
Text GLabel 3550 3150 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 3250 2    50   Input ~ 0
DQ32_MB
Text GLabel 3550 3350 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 3450 2    50   Input ~ 0
DQS13_t_TDQ13_t_MB
Text GLabel 3550 3550 2    50   Input ~ 0
DQS13_c_TDQS13_c_MB
Text GLabel 3550 3650 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 3750 2    50   Input ~ 0
DQ38_MB
Text GLabel 3550 3850 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 3950 2    50   Input ~ 0
DQ34_MB
Text GLabel 3550 4050 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 4150 2    50   Input ~ 0
DQ44_MB
Text GLabel 3550 4250 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 4350 2    50   Input ~ 0
DQ40_MB
Text GLabel 3550 4450 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 4550 2    50   Input ~ 0
DQS14_t_TDQS14_t_MB
Text GLabel 3550 4650 2    50   Input ~ 0
DQS14_c_TDQS14_c_MB
Text GLabel 3550 4750 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 4850 2    50   Input ~ 0
DQ46_MB
Text GLabel 3550 4950 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 5050 2    50   Input ~ 0
DQ42_MB
Text GLabel 3550 5150 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 5250 2    50   Input ~ 0
DQ52_MB
Text GLabel 3550 5350 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 5450 2    50   Input ~ 0
DQ48_MB
Text GLabel 3550 5550 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 5650 2    50   Input ~ 0
DQS15_t_TDQS15_t_MB
Text GLabel 3550 5750 2    50   Input ~ 0
DQS15_c_TDQS15_c_MB
Text GLabel 3550 5850 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 5950 2    50   Input ~ 0
DQ54_MB
Text GLabel 3550 6050 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 6150 2    50   Input ~ 0
DQ50_MB
Text GLabel 3550 6250 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 6350 2    50   Input ~ 0
DQ60_MB
Text GLabel 3550 6450 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 6550 2    50   Input ~ 0
DQ56_MB
Text GLabel 3550 6650 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 6750 2    50   Input ~ 0
DQS16_t_TDQS16_t_MB
Text GLabel 3550 6850 2    50   Input ~ 0
DQS16_c_TDQS16_c_MB
Text GLabel 3550 6950 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 7050 2    50   Input ~ 0
DQ62_MB
Text GLabel 3550 7150 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 7250 2    50   Input ~ 0
DQ58_MB
Text GLabel 3550 7350 2    50   Input ~ 0
VSS_MB
Text GLabel 3550 7450 2    50   Input ~ 0
SA0_MB
Text GLabel 3550 7550 2    50   Input ~ 0
SA1_MB
Text GLabel 3550 7650 2    50   Input ~ 0
SCL_MB
Text GLabel 3550 7750 2    50   Input ~ 0
VPP_MB
Text GLabel 3550 7850 2    50   Input ~ 0
VPP_MB
Text GLabel 3550 7950 2    50   Input ~ 0
NC_MB
Text GLabel 5150 850  0    50   Input ~ 0
NC_MB
Text GLabel 5150 950  0    50   Input ~ 0
VREFCA_MB
Text GLabel 5150 1050 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 1150 0    50   Input ~ 0
DQ5_MB
Text GLabel 5150 1250 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 1350 0    50   Input ~ 0
DQ1_MB
Text GLabel 5150 1450 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 1550 0    50   Input ~ 0
DQS0_c_MB
Text GLabel 5150 1650 0    50   Input ~ 0
DQS0_t_MB
Text GLabel 5150 1750 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 1850 0    50   Input ~ 0
DQ7_MB
Text GLabel 5150 1950 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 2050 0    50   Input ~ 0
DQ3_MB
Text GLabel 5150 2150 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 2250 0    50   Input ~ 0
DQ13_MB
Text GLabel 5150 2350 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 2450 0    50   Input ~ 0
DQ9_MB
Text GLabel 5150 2550 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 2650 0    50   Input ~ 0
DQS1_c_MB
Text GLabel 5150 2750 0    50   Input ~ 0
DQS1_t_MB
Text GLabel 5150 2850 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 2950 0    50   Input ~ 0
DQ15_MB
Text GLabel 5150 3050 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 3150 0    50   Input ~ 0
DQ11_MB
Text GLabel 5150 3250 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 3350 0    50   Input ~ 0
DQ21_MB
Text GLabel 5150 3450 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 3550 0    50   Input ~ 0
DQ17_MB
Text GLabel 5150 3650 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 3750 0    50   Input ~ 0
DQS2_c_MB
Text GLabel 5150 3850 0    50   Input ~ 0
DQS2_t_MB
Text GLabel 5150 3950 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 4050 0    50   Input ~ 0
DQ23_MB
Text GLabel 5150 4150 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 4250 0    50   Input ~ 0
DQ19_MB
Text GLabel 5150 4350 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 4450 0    50   Input ~ 0
DQ29_MB
Text GLabel 5150 4550 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 4650 0    50   Input ~ 0
DQ25_MB
Text GLabel 5150 4750 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 4850 0    50   Input ~ 0
DQS3_c_MB
Text GLabel 5150 4950 0    50   Input ~ 0
DQS3_t_MB
Text GLabel 5150 5050 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 5150 0    50   Input ~ 0
DQ31_MB
Text GLabel 5150 5250 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 5350 0    50   Input ~ 0
DQ27_MB
Text GLabel 5150 5450 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 5550 0    50   Input ~ 0
CB5_MB
Text GLabel 5150 5650 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 5750 0    50   Input ~ 0
CB1_MB
Text GLabel 5150 5850 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 5950 0    50   Input ~ 0
DQS8_c_MB
Text GLabel 5150 6050 0    50   Input ~ 0
DQS8_t_MB
Text GLabel 5150 6150 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 6250 0    50   Input ~ 0
CB7_MB
Text GLabel 5150 6350 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 6450 0    50   Input ~ 0
CB3_MB
Text GLabel 5150 6550 0    50   Input ~ 0
VSS_MB
Text GLabel 5150 6650 0    50   Input ~ 0
CKE1_NC_MB
Text GLabel 5150 6750 0    50   Input ~ 0
VDD_MB
Text GLabel 5150 6850 0    50   Input ~ 0
NC_MB
Text GLabel 5150 6950 0    50   Input ~ 0
VDD_MB
Text GLabel 5150 7050 0    50   Input ~ 0
BG1_MB
Text GLabel 5150 7150 0    50   Input ~ 0
ALERT_n_MB
Text GLabel 5150 7250 0    50   Input ~ 0
VDD_MB
Text GLabel 5150 7350 0    50   Input ~ 0
A11_MB
Text GLabel 5150 7450 0    50   Input ~ 0
A7_MB
Text GLabel 5150 7550 0    50   Input ~ 0
VDD_MB
Text GLabel 5150 7650 0    50   Input ~ 0
A5_MB
Text GLabel 5150 7750 0    50   Input ~ 0
A4_MB
Text GLabel 5150 7850 0    50   Input ~ 0
VDD_MB
Text GLabel 5150 7950 0    50   Input ~ 0
A2_MB
Text GLabel 6550 850  2    50   Input ~ 0
VDD_MB
Text GLabel 6550 950  2    50   Input ~ 0
CK1_t_MB
Text GLabel 6550 1050 2    50   Input ~ 0
CK1_c_MB
Text GLabel 6550 1150 2    50   Input ~ 0
VDD_MB
Text GLabel 6550 1250 2    50   Input ~ 0
VTT_MB
Text GLabel 6550 1350 2    50   Input ~ 0
PARITY_MB
Text GLabel 6550 1450 2    50   Input ~ 0
VDD_MB
Text GLabel 6550 1550 2    50   Input ~ 0
BA1_MB
Text GLabel 6550 1650 2    50   Input ~ 0
A10_AP_MB
Text GLabel 6550 1750 2    50   Input ~ 0
VDD_MB
Text GLabel 6550 1850 2    50   Input ~ 0
NC_MB
Text GLabel 6550 1950 2    50   Input ~ 0
WE_n_A14_MB
Text GLabel 6550 2050 2    50   Input ~ 0
VDD_MB
Text GLabel 6550 2150 2    50   Input ~ 0
NC_MB
Text GLabel 6550 2250 2    50   Input ~ 0
VDD_MB
Text GLabel 6550 2350 2    50   Input ~ 0
A13_MB
Text GLabel 6550 2450 2    50   Input ~ 0
VDD_MB
Text GLabel 6550 2550 2    50   Input ~ 0
A17_MB
Text GLabel 6550 2650 2    50   Input ~ 0
NC_C2_MB
Text GLabel 6550 2750 2    50   Input ~ 0
VDD_MB
Text GLabel 6550 2850 2    50   Input ~ 0
CS3_n_C1,NC_MB
Text GLabel 6550 2950 2    50   Input ~ 0
SA2_MB
Text GLabel 6550 3050 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 3150 2    50   Input ~ 0
DQ37_MB
Text GLabel 6550 3250 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 3350 2    50   Input ~ 0
DQ33_MB
Text GLabel 6550 3450 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 3550 2    50   Input ~ 0
DQS4_c_MB
Text GLabel 6550 3650 2    50   Input ~ 0
DQS4_t_MB
Text GLabel 6550 3750 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 3850 2    50   Input ~ 0
DQ39_MB
Text GLabel 6550 3950 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 4050 2    50   Input ~ 0
DQ35_MB
Text GLabel 6550 4150 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 4250 2    50   Input ~ 0
DQ45_MB
Text GLabel 6550 4350 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 4450 2    50   Input ~ 0
DQ41_MB
Text GLabel 6550 4550 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 4650 2    50   Input ~ 0
DQS5_c_MB
Text GLabel 6550 4750 2    50   Input ~ 0
DQS5_t_MB
Text GLabel 6550 4850 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 4950 2    50   Input ~ 0
DQ47_MB
Text GLabel 6550 5050 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 5150 2    50   Input ~ 0
DQ43_MB
Text GLabel 6550 5250 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 5350 2    50   Input ~ 0
DQ53_MB
Text GLabel 6550 5450 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 5550 2    50   Input ~ 0
DQ49_MB
Text GLabel 6550 5650 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 5750 2    50   Input ~ 0
DQS6_c_MB
Text GLabel 6550 5850 2    50   Input ~ 0
DQS6_t_MB
Text GLabel 6550 5950 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 6050 2    50   Input ~ 0
DQ55_MB
Text GLabel 6550 6150 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 6250 2    50   Input ~ 0
DQ51_MB
Text GLabel 6550 6350 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 6450 2    50   Input ~ 0
DQ61_MB
Text GLabel 6550 6550 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 6650 2    50   Input ~ 0
DQ57_MB
Text GLabel 6550 6750 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 6850 2    50   Input ~ 0
DQS7_c_MB
Text GLabel 6550 6950 2    50   Input ~ 0
DQS7_t_MB
Text GLabel 6550 7050 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 7150 2    50   Input ~ 0
DQ63_MB
Text GLabel 6550 7250 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 7350 2    50   Input ~ 0
DQ59_MB
Text GLabel 6550 7450 2    50   Input ~ 0
VSS_MB
Text GLabel 6550 7550 2    50   Input ~ 0
VDDSPD_MB
Text GLabel 6550 7650 2    50   Input ~ 0
SDA_MB
Text GLabel 6550 7750 2    50   Input ~ 0
VPP_MB
Text GLabel 6550 7850 2    50   Input ~ 0
VPP_MB
Text GLabel 6550 7950 2    50   Input ~ 0
VPP_MB
$EndSCHEMATC
