EESchema Schematic File Version 4
EELAYER 30 0
EELAYER END
$Descr USLetter 8500 11000 portrait
encoding utf-8
Sheet 4 5
Title "Direct connections between the DIMM and the Mother Board"
Date "2019-11-01"
Rev "1"
Comp ""
Comment1 "Autogenerated. See misc/check-ddr4.py"
Comment2 ""
Comment3 ""
Comment4 ""
$EndDescr
Wire Wire Line
	1200 600  1300 600 
Text GLabel 1200 600  0    50   Input ~ 0
NC_MB
Text GLabel 1300 600  2    50   Input ~ 0
NC_DIMM
Wire Wire Line
	1200 700  1300 700 
Text GLabel 1200 700  0    50   Input ~ 0
VSS_MB
Text GLabel 1300 700  2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 800  1300 800 
Text GLabel 1200 800  0    50   Input ~ 0
DQ4_MB
Text GLabel 1300 800  2    50   Input ~ 0
DQ4_DIMM
Wire Wire Line
	1200 900  1300 900 
Text GLabel 1200 900  0    50   Input ~ 0
VSS_MB
Text GLabel 1300 900  2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 1000 1300 1000
Text GLabel 1200 1000 0    50   Input ~ 0
DQ0_MB
Text GLabel 1300 1000 2    50   Input ~ 0
DQ0_DIMM
Wire Wire Line
	1200 1100 1300 1100
Text GLabel 1200 1100 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 1100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 1200 1300 1200
Text GLabel 1200 1200 0    50   Input ~ 0
DQS9_t_TDQS9_t_MB
Text GLabel 1300 1200 2    50   Input ~ 0
DQS9_t_TDQS9_t_DIMM
Wire Wire Line
	1200 1300 1300 1300
Text GLabel 1200 1300 0    50   Input ~ 0
DQS09_c_TDQS9_c_MB
Text GLabel 1300 1300 2    50   Input ~ 0
DQS09_c_TDQS9_c_DIMM
Wire Wire Line
	1200 1400 1300 1400
Text GLabel 1200 1400 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 1400 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 1500 1300 1500
Text GLabel 1200 1500 0    50   Input ~ 0
DQ6_MB
Text GLabel 1300 1500 2    50   Input ~ 0
DQ6_DIMM
Wire Wire Line
	1200 1600 1300 1600
Text GLabel 1200 1600 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 1600 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 1700 1300 1700
Text GLabel 1200 1700 0    50   Input ~ 0
DQ2_MB
Text GLabel 1300 1700 2    50   Input ~ 0
DQ2_DIMM
Wire Wire Line
	1200 1800 1300 1800
Text GLabel 1200 1800 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 1800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 1900 1300 1900
Text GLabel 1200 1900 0    50   Input ~ 0
DQ12_MB
Text GLabel 1300 1900 2    50   Input ~ 0
DQ12_DIMM
Wire Wire Line
	1200 2000 1300 2000
Text GLabel 1200 2000 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 2000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 2100 1300 2100
Text GLabel 1200 2100 0    50   Input ~ 0
DQ8_MB
Text GLabel 1300 2100 2    50   Input ~ 0
DQ8_DIMM
Wire Wire Line
	1200 2200 1300 2200
Text GLabel 1200 2200 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 2200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 2300 1300 2300
Text GLabel 1200 2300 0    50   Input ~ 0
DQS10_t_TDQS10_t_MB
Text GLabel 1300 2300 2    50   Input ~ 0
DQS10_t_TDQS10_t_DIMM
Wire Wire Line
	1200 2400 1300 2400
Text GLabel 1200 2400 0    50   Input ~ 0
DQS10_c_TDQS10_c_MB
Text GLabel 1300 2400 2    50   Input ~ 0
DQS10_c_TDQS10_c_DIMM
Wire Wire Line
	1200 2500 1300 2500
Text GLabel 1200 2500 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 2500 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 2600 1300 2600
Text GLabel 1200 2600 0    50   Input ~ 0
DQ14_MB
Text GLabel 1300 2600 2    50   Input ~ 0
DQ14_DIMM
Wire Wire Line
	1200 2700 1300 2700
Text GLabel 1200 2700 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 2700 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 2800 1300 2800
Text GLabel 1200 2800 0    50   Input ~ 0
DQ10_MB
Text GLabel 1300 2800 2    50   Input ~ 0
DQ10_DIMM
Wire Wire Line
	1200 2900 1300 2900
Text GLabel 1200 2900 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 2900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 3000 1300 3000
Text GLabel 1200 3000 0    50   Input ~ 0
DQ20_MB
Text GLabel 1300 3000 2    50   Input ~ 0
DQ20_DIMM
Wire Wire Line
	1200 3100 1300 3100
Text GLabel 1200 3100 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 3100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 3200 1300 3200
Text GLabel 1200 3200 0    50   Input ~ 0
DQ16_MB
Text GLabel 1300 3200 2    50   Input ~ 0
DQ16_DIMM
Wire Wire Line
	1200 3300 1300 3300
Text GLabel 1200 3300 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 3300 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 3400 1300 3400
Text GLabel 1200 3400 0    50   Input ~ 0
DQS11_t_TDQS11_t_MB
Text GLabel 1300 3400 2    50   Input ~ 0
DQS11_t_TDQS11_t_DIMM
Wire Wire Line
	1200 3500 1300 3500
Text GLabel 1200 3500 0    50   Input ~ 0
DQS11_c_TDQS11_c_MB
Text GLabel 1300 3500 2    50   Input ~ 0
DQS11_c_TDQS11_c_DIMM
Wire Wire Line
	1200 3600 1300 3600
Text GLabel 1200 3600 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 3600 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 3700 1300 3700
Text GLabel 1200 3700 0    50   Input ~ 0
DQ22_MB
Text GLabel 1300 3700 2    50   Input ~ 0
DQ22_DIMM
Wire Wire Line
	1200 3800 1300 3800
Text GLabel 1200 3800 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 3800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 3900 1300 3900
Text GLabel 1200 3900 0    50   Input ~ 0
DQ18_MB
Text GLabel 1300 3900 2    50   Input ~ 0
DQ18_DIMM
Wire Wire Line
	1200 4000 1300 4000
Text GLabel 1200 4000 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 4000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 4100 1300 4100
Text GLabel 1200 4100 0    50   Input ~ 0
DQ28_MB
Text GLabel 1300 4100 2    50   Input ~ 0
DQ28_DIMM
Wire Wire Line
	1200 4200 1300 4200
Text GLabel 1200 4200 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 4200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 4300 1300 4300
Text GLabel 1200 4300 0    50   Input ~ 0
DQ24_MB
Text GLabel 1300 4300 2    50   Input ~ 0
DQ24_DIMM
Wire Wire Line
	1200 4400 1300 4400
Text GLabel 1200 4400 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 4400 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 4500 1300 4500
Text GLabel 1200 4500 0    50   Input ~ 0
DQS12_t_TDQS12_t_MB
Text GLabel 1300 4500 2    50   Input ~ 0
DQS12_t_TDQS12_t_DIMM
Wire Wire Line
	1200 4600 1300 4600
Text GLabel 1200 4600 0    50   Input ~ 0
DQS12_c_TDQS12_c_MB
Text GLabel 1300 4600 2    50   Input ~ 0
DQS12_c_TDQS12_c_DIMM
Wire Wire Line
	1200 4700 1300 4700
Text GLabel 1200 4700 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 4700 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 4800 1300 4800
Text GLabel 1200 4800 0    50   Input ~ 0
DQ30_MB
Text GLabel 1300 4800 2    50   Input ~ 0
DQ30_DIMM
Wire Wire Line
	1200 4900 1300 4900
Text GLabel 1200 4900 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 4900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 5000 1300 5000
Text GLabel 1200 5000 0    50   Input ~ 0
DQ26_MB
Text GLabel 1300 5000 2    50   Input ~ 0
DQ26_DIMM
Wire Wire Line
	1200 5100 1300 5100
Text GLabel 1200 5100 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 5100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 5200 1300 5200
Text GLabel 1200 5200 0    50   Input ~ 0
CB4_MB
Text GLabel 1300 5200 2    50   Input ~ 0
CB4_DIMM
Wire Wire Line
	1200 5300 1300 5300
Text GLabel 1200 5300 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 5300 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 5400 1300 5400
Text GLabel 1200 5400 0    50   Input ~ 0
CB0_MB
Text GLabel 1300 5400 2    50   Input ~ 0
CB0_DIMM
Wire Wire Line
	1200 5500 1300 5500
Text GLabel 1200 5500 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 5500 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 5600 1300 5600
Text GLabel 1200 5600 0    50   Input ~ 0
DQS17_t_TDQS17_t_MB
Text GLabel 1300 5600 2    50   Input ~ 0
DQS17_t_TDQS17_t_DIMM
Wire Wire Line
	1200 5700 1300 5700
Text GLabel 1200 5700 0    50   Input ~ 0
DQS17_c_TDQS17_c_MB
Text GLabel 1300 5700 2    50   Input ~ 0
DQS17_c_TDQS17_c_DIMM
Wire Wire Line
	1200 5800 1300 5800
Text GLabel 1200 5800 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 5800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 5900 1300 5900
Text GLabel 1200 5900 0    50   Input ~ 0
CB6_MB
Text GLabel 1300 5900 2    50   Input ~ 0
CB6_DIMM
Wire Wire Line
	1200 6000 1300 6000
Text GLabel 1200 6000 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 6000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 6100 1300 6100
Text GLabel 1200 6100 0    50   Input ~ 0
CB2_MB
Text GLabel 1300 6100 2    50   Input ~ 0
CB2_DIMM
Wire Wire Line
	1200 6200 1300 6200
Text GLabel 1200 6200 0    50   Input ~ 0
VSS_MB
Text GLabel 1300 6200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	1200 6300 1300 6300
Text GLabel 1200 6300 0    50   Input ~ 0
RESET_n_MB
Text GLabel 1300 6300 2    50   Input ~ 0
RESET_n_DIMM
Wire Wire Line
	1200 6400 1300 6400
Text GLabel 1200 6400 0    50   Input ~ 0
VDD_MB
Text GLabel 1300 6400 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	1200 6500 1300 6500
Text GLabel 1200 6500 0    50   Input ~ 0
CKE0_MB
Text GLabel 1300 6500 2    50   Input ~ 0
CKE0_DIMM
Wire Wire Line
	1200 6600 1300 6600
Text GLabel 1200 6600 0    50   Input ~ 0
VDD_MB
Text GLabel 1300 6600 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	1200 6700 1300 6700
Text GLabel 1200 6700 0    50   Input ~ 0
ACT_n_MB
Text GLabel 1300 6700 2    50   Input ~ 0
ACT_n_DIMM
Wire Wire Line
	1200 6800 1300 6800
Text GLabel 1200 6800 0    50   Input ~ 0
BG0_MB
Text GLabel 1300 6800 2    50   Input ~ 0
BG0_DIMM
Wire Wire Line
	1200 6900 1300 6900
Text GLabel 1200 6900 0    50   Input ~ 0
VDD_MB
Text GLabel 1300 6900 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	1200 7000 1300 7000
Text GLabel 1200 7000 0    50   Input ~ 0
A12_BC_n_MB
Text GLabel 1300 7000 2    50   Input ~ 0
A12_BC_n_DIMM
Wire Wire Line
	1200 7100 1300 7100
Text GLabel 1200 7100 0    50   Input ~ 0
A9_MB
Text GLabel 1300 7100 2    50   Input ~ 0
A9_DIMM
Wire Wire Line
	1200 7200 1300 7200
Text GLabel 1200 7200 0    50   Input ~ 0
VDD_MB
Text GLabel 1300 7200 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	1200 7300 1300 7300
Text GLabel 1200 7300 0    50   Input ~ 0
A8_MB
Text GLabel 1300 7300 2    50   Input ~ 0
A8_DIMM
Wire Wire Line
	1200 7400 1300 7400
Text GLabel 1200 7400 0    50   Input ~ 0
A6_MB
Text GLabel 1300 7400 2    50   Input ~ 0
A6_DIMM
Wire Wire Line
	1200 7500 1300 7500
Text GLabel 1200 7500 0    50   Input ~ 0
VDD_MB
Text GLabel 1300 7500 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	1200 7600 1300 7600
Text GLabel 1200 7600 0    50   Input ~ 0
A3_MB
Text GLabel 1300 7600 2    50   Input ~ 0
A3_DIMM
Wire Wire Line
	1200 7700 1300 7700
Text GLabel 1200 7700 0    50   Input ~ 0
A1_MB
Text GLabel 1300 7700 2    50   Input ~ 0
A1_DIMM
Wire Wire Line
	2800 600  2900 600 
Text GLabel 2800 600  0    50   Input ~ 0
VDD_MB
Text GLabel 2900 600  2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	2800 700  2900 700 
Text GLabel 2800 700  0    50   Input ~ 0
CK0_t_MB
Text GLabel 2900 700  2    50   Input ~ 0
CK0_t_DIMM
Wire Wire Line
	2800 800  2900 800 
Text GLabel 2800 800  0    50   Input ~ 0
CK0_c_MB
Text GLabel 2900 800  2    50   Input ~ 0
CK0_c_DIMM
Wire Wire Line
	2800 900  2900 900 
Text GLabel 2800 900  0    50   Input ~ 0
VDD_MB
Text GLabel 2900 900  2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	2800 1000 2900 1000
Text GLabel 2800 1000 0    50   Input ~ 0
VTT_MB
Text GLabel 2900 1000 2    50   Input ~ 0
VTT_DIMM
Wire Wire Line
	2800 1100 2900 1100
Text GLabel 2800 1100 0    50   Input ~ 0
EVENT_n_MB
Text GLabel 2900 1100 2    50   Input ~ 0
EVENT_n_DIMM
Wire Wire Line
	2800 1200 2900 1200
Text GLabel 2800 1200 0    50   Input ~ 0
A0_MB
Text GLabel 2900 1200 2    50   Input ~ 0
A0_DIMM
Wire Wire Line
	2800 1300 2900 1300
Text GLabel 2800 1300 0    50   Input ~ 0
VDD_MB
Text GLabel 2900 1300 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	2800 1400 2900 1400
Text GLabel 2800 1400 0    50   Input ~ 0
BA0_MB
Text GLabel 2900 1400 2    50   Input ~ 0
BA0_DIMM
Wire Wire Line
	2800 1500 2900 1500
Text GLabel 2800 1500 0    50   Input ~ 0
RAS_n_A16_MB
Text GLabel 2900 1500 2    50   Input ~ 0
RAS_n_A16_DIMM
Wire Wire Line
	2800 1600 2900 1600
Text GLabel 2800 1600 0    50   Input ~ 0
VDD_MB
Text GLabel 2900 1600 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	2800 1700 2900 1700
Text GLabel 2800 1700 0    50   Input ~ 0
CS0_n_MB
Text GLabel 2900 1700 2    50   Input ~ 0
CS0_n_DIMM
Wire Wire Line
	2800 1800 2900 1800
Text GLabel 2800 1800 0    50   Input ~ 0
VDD_MB
Text GLabel 2900 1800 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	2800 1900 2900 1900
Text GLabel 2800 1900 0    50   Input ~ 0
CAS_n_A15_MB
Text GLabel 2900 1900 2    50   Input ~ 0
CAS_n_A15_DIMM
Wire Wire Line
	2800 2000 2900 2000
Text GLabel 2800 2000 0    50   Input ~ 0
ODT0_MB
Text GLabel 2900 2000 2    50   Input ~ 0
ODT0_DIMM
Wire Wire Line
	2800 2100 2900 2100
Text GLabel 2800 2100 0    50   Input ~ 0
VDD_MB
Text GLabel 2900 2100 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	2800 2200 2900 2200
Text GLabel 2800 2200 0    50   Input ~ 0
CS1_n_NC_MB
Text GLabel 2900 2200 2    50   Input ~ 0
CS1_n_NC_DIMM
Wire Wire Line
	2800 2300 2900 2300
Text GLabel 2800 2300 0    50   Input ~ 0
VDD_MB
Text GLabel 2900 2300 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	2800 2400 2900 2400
Text GLabel 2800 2400 0    50   Input ~ 0
ODT1_NC_MB
Text GLabel 2900 2400 2    50   Input ~ 0
ODT1_NC_DIMM
Wire Wire Line
	2800 2500 2900 2500
Text GLabel 2800 2500 0    50   Input ~ 0
VDD_MB
Text GLabel 2900 2500 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	2800 2600 2900 2600
Text GLabel 2800 2600 0    50   Input ~ 0
CS2_n_C0_MB
Text GLabel 2900 2600 2    50   Input ~ 0
CS2_n_C0_DIMM
Wire Wire Line
	2800 2700 2900 2700
Text GLabel 2800 2700 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 2700 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 2800 2900 2800
Text GLabel 2800 2800 0    50   Input ~ 0
DQ36_MB
Text GLabel 2900 2800 2    50   Input ~ 0
DQ36_DIMM
Wire Wire Line
	2800 2900 2900 2900
Text GLabel 2800 2900 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 2900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 3000 2900 3000
Text GLabel 2800 3000 0    50   Input ~ 0
DQ32_MB
Text GLabel 2900 3000 2    50   Input ~ 0
DQ32_DIMM
Wire Wire Line
	2800 3100 2900 3100
Text GLabel 2800 3100 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 3100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 3200 2900 3200
Text GLabel 2800 3200 0    50   Input ~ 0
DQS13_t_TDQ13_t_MB
Text GLabel 2900 3200 2    50   Input ~ 0
DQS13_t_TDQ13_t_DIMM
Wire Wire Line
	2800 3300 2900 3300
Text GLabel 2800 3300 0    50   Input ~ 0
DQS13_c_TDQS13_c_MB
Text GLabel 2900 3300 2    50   Input ~ 0
DQS13_c_TDQS13_c_DIMM
Wire Wire Line
	2800 3400 2900 3400
Text GLabel 2800 3400 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 3400 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 3500 2900 3500
Text GLabel 2800 3500 0    50   Input ~ 0
DQ38_MB
Text GLabel 2900 3500 2    50   Input ~ 0
DQ38_DIMM
Wire Wire Line
	2800 3600 2900 3600
Text GLabel 2800 3600 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 3600 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 3700 2900 3700
Text GLabel 2800 3700 0    50   Input ~ 0
DQ34_MB
Text GLabel 2900 3700 2    50   Input ~ 0
DQ34_DIMM
Wire Wire Line
	2800 3800 2900 3800
Text GLabel 2800 3800 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 3800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 3900 2900 3900
Text GLabel 2800 3900 0    50   Input ~ 0
DQ44_MB
Text GLabel 2900 3900 2    50   Input ~ 0
DQ44_DIMM
Wire Wire Line
	2800 4000 2900 4000
Text GLabel 2800 4000 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 4000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 4100 2900 4100
Text GLabel 2800 4100 0    50   Input ~ 0
DQ40_MB
Text GLabel 2900 4100 2    50   Input ~ 0
DQ40_DIMM
Wire Wire Line
	2800 4200 2900 4200
Text GLabel 2800 4200 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 4200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 4300 2900 4300
Text GLabel 2800 4300 0    50   Input ~ 0
DQS14_t_TDQS14_t_MB
Text GLabel 2900 4300 2    50   Input ~ 0
DQS14_t_TDQS14_t_DIMM
Wire Wire Line
	2800 4400 2900 4400
Text GLabel 2800 4400 0    50   Input ~ 0
DQS14_c_TDQS14_c_MB
Text GLabel 2900 4400 2    50   Input ~ 0
DQS14_c_TDQS14_c_DIMM
Wire Wire Line
	2800 4500 2900 4500
Text GLabel 2800 4500 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 4500 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 4600 2900 4600
Text GLabel 2800 4600 0    50   Input ~ 0
DQ46_MB
Text GLabel 2900 4600 2    50   Input ~ 0
DQ46_DIMM
Wire Wire Line
	2800 4700 2900 4700
Text GLabel 2800 4700 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 4700 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 4800 2900 4800
Text GLabel 2800 4800 0    50   Input ~ 0
DQ42_MB
Text GLabel 2900 4800 2    50   Input ~ 0
DQ42_DIMM
Wire Wire Line
	2800 4900 2900 4900
Text GLabel 2800 4900 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 4900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 5000 2900 5000
Text GLabel 2800 5000 0    50   Input ~ 0
DQ52_MB
Text GLabel 2900 5000 2    50   Input ~ 0
DQ52_DIMM
Wire Wire Line
	2800 5100 2900 5100
Text GLabel 2800 5100 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 5100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 5200 2900 5200
Text GLabel 2800 5200 0    50   Input ~ 0
DQ48_MB
Text GLabel 2900 5200 2    50   Input ~ 0
DQ48_DIMM
Wire Wire Line
	2800 5300 2900 5300
Text GLabel 2800 5300 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 5300 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 5400 2900 5400
Text GLabel 2800 5400 0    50   Input ~ 0
DQS15_t_TDQS15_t_MB
Text GLabel 2900 5400 2    50   Input ~ 0
DQS15_t_TDQS15_t_DIMM
Wire Wire Line
	2800 5500 2900 5500
Text GLabel 2800 5500 0    50   Input ~ 0
DQS15_c_TDQS15_c_MB
Text GLabel 2900 5500 2    50   Input ~ 0
DQS15_c_TDQS15_c_DIMM
Wire Wire Line
	2800 5600 2900 5600
Text GLabel 2800 5600 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 5600 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 5700 2900 5700
Text GLabel 2800 5700 0    50   Input ~ 0
DQ54_MB
Text GLabel 2900 5700 2    50   Input ~ 0
DQ54_DIMM
Wire Wire Line
	2800 5800 2900 5800
Text GLabel 2800 5800 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 5800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 5900 2900 5900
Text GLabel 2800 5900 0    50   Input ~ 0
DQ50_MB
Text GLabel 2900 5900 2    50   Input ~ 0
DQ50_DIMM
Wire Wire Line
	2800 6000 2900 6000
Text GLabel 2800 6000 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 6000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 6100 2900 6100
Text GLabel 2800 6100 0    50   Input ~ 0
DQ60_MB
Text GLabel 2900 6100 2    50   Input ~ 0
DQ60_DIMM
Wire Wire Line
	2800 6200 2900 6200
Text GLabel 2800 6200 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 6200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 6300 2900 6300
Text GLabel 2800 6300 0    50   Input ~ 0
DQ56_MB
Text GLabel 2900 6300 2    50   Input ~ 0
DQ56_DIMM
Wire Wire Line
	2800 6400 2900 6400
Text GLabel 2800 6400 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 6400 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 6500 2900 6500
Text GLabel 2800 6500 0    50   Input ~ 0
DQS16_t_TDQS16_t_MB
Text GLabel 2900 6500 2    50   Input ~ 0
DQS16_t_TDQS16_t_DIMM
Wire Wire Line
	2800 6600 2900 6600
Text GLabel 2800 6600 0    50   Input ~ 0
DQS16_c_TDQS16_c_MB
Text GLabel 2900 6600 2    50   Input ~ 0
DQS16_c_TDQS16_c_DIMM
Wire Wire Line
	2800 6700 2900 6700
Text GLabel 2800 6700 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 6700 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 6800 2900 6800
Text GLabel 2800 6800 0    50   Input ~ 0
DQ62_MB
Text GLabel 2900 6800 2    50   Input ~ 0
DQ62_DIMM
Wire Wire Line
	2800 6900 2900 6900
Text GLabel 2800 6900 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 6900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 7000 2900 7000
Text GLabel 2800 7000 0    50   Input ~ 0
DQ58_MB
Text GLabel 2900 7000 2    50   Input ~ 0
DQ58_DIMM
Wire Wire Line
	2800 7100 2900 7100
Text GLabel 2800 7100 0    50   Input ~ 0
VSS_MB
Text GLabel 2900 7100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	2800 7200 2900 7200
Text GLabel 2800 7200 0    50   Input ~ 0
SA0_MB
Text GLabel 2900 7200 2    50   Input ~ 0
SA0_DIMM
Wire Wire Line
	2800 7300 2900 7300
Text GLabel 2800 7300 0    50   Input ~ 0
SA1_MB
Text GLabel 2900 7300 2    50   Input ~ 0
SA1_DIMM
Wire Wire Line
	2800 7400 2900 7400
Text GLabel 2800 7400 0    50   Input ~ 0
SCL_MB
Text GLabel 2900 7400 2    50   Input ~ 0
SCL_DIMM
Wire Wire Line
	2800 7500 2900 7500
Text GLabel 2800 7500 0    50   Input ~ 0
VPP_MB
Text GLabel 2900 7500 2    50   Input ~ 0
VPP_DIMM
Wire Wire Line
	2800 7600 2900 7600
Text GLabel 2800 7600 0    50   Input ~ 0
VPP_MB
Text GLabel 2900 7600 2    50   Input ~ 0
VPP_DIMM
Wire Wire Line
	2800 7700 2900 7700
Text GLabel 2800 7700 0    50   Input ~ 0
NC_MB
Text GLabel 2900 7700 2    50   Input ~ 0
NC_DIMM
Wire Wire Line
	5200 600  5300 600 
Text GLabel 5200 600  0    50   Input ~ 0
NC_MB
Text GLabel 5300 600  2    50   Input ~ 0
NC_DIMM
Wire Wire Line
	5200 700  5300 700 
Text GLabel 5200 700  0    50   Input ~ 0
VREFCA_MB
Text GLabel 5300 700  2    50   Input ~ 0
VREFCA_DIMM
Wire Wire Line
	5200 800  5300 800 
Text GLabel 5200 800  0    50   Input ~ 0
VSS_MB
Text GLabel 5300 800  2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 900  5300 900 
Text GLabel 5200 900  0    50   Input ~ 0
DQ5_MB
Text GLabel 5300 900  2    50   Input ~ 0
DQ5_DIMM
Wire Wire Line
	5200 1000 5300 1000
Text GLabel 5200 1000 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 1000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 1100 5300 1100
Text GLabel 5200 1100 0    50   Input ~ 0
DQ1_MB
Text GLabel 5300 1100 2    50   Input ~ 0
DQ1_DIMM
Wire Wire Line
	5200 1200 5300 1200
Text GLabel 5200 1200 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 1200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 1300 5300 1300
Text GLabel 5200 1300 0    50   Input ~ 0
DQS0_c_MB
Text GLabel 5300 1300 2    50   Input ~ 0
DQS0_c_DIMM
Wire Wire Line
	5200 1400 5300 1400
Text GLabel 5200 1400 0    50   Input ~ 0
DQS0_t_MB
Text GLabel 5300 1400 2    50   Input ~ 0
DQS0_t_DIMM
Wire Wire Line
	5200 1500 5300 1500
Text GLabel 5200 1500 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 1500 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 1600 5300 1600
Text GLabel 5200 1600 0    50   Input ~ 0
DQ7_MB
Text GLabel 5300 1600 2    50   Input ~ 0
DQ7_DIMM
Wire Wire Line
	5200 1700 5300 1700
Text GLabel 5200 1700 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 1700 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 1800 5300 1800
Text GLabel 5200 1800 0    50   Input ~ 0
DQ3_MB
Text GLabel 5300 1800 2    50   Input ~ 0
DQ3_DIMM
Wire Wire Line
	5200 1900 5300 1900
Text GLabel 5200 1900 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 1900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 2000 5300 2000
Text GLabel 5200 2000 0    50   Input ~ 0
DQ13_MB
Text GLabel 5300 2000 2    50   Input ~ 0
DQ13_DIMM
Wire Wire Line
	5200 2100 5300 2100
Text GLabel 5200 2100 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 2100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 2200 5300 2200
Text GLabel 5200 2200 0    50   Input ~ 0
DQ9_MB
Text GLabel 5300 2200 2    50   Input ~ 0
DQ9_DIMM
Wire Wire Line
	5200 2300 5300 2300
Text GLabel 5200 2300 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 2300 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 2400 5300 2400
Text GLabel 5200 2400 0    50   Input ~ 0
DQS1_c_MB
Text GLabel 5300 2400 2    50   Input ~ 0
DQS1_c_DIMM
Wire Wire Line
	5200 2500 5300 2500
Text GLabel 5200 2500 0    50   Input ~ 0
DQS1_t_MB
Text GLabel 5300 2500 2    50   Input ~ 0
DQS1_t_DIMM
Wire Wire Line
	5200 2600 5300 2600
Text GLabel 5200 2600 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 2600 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 2700 5300 2700
Text GLabel 5200 2700 0    50   Input ~ 0
DQ15_MB
Text GLabel 5300 2700 2    50   Input ~ 0
DQ15_DIMM
Wire Wire Line
	5200 2800 5300 2800
Text GLabel 5200 2800 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 2800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 2900 5300 2900
Text GLabel 5200 2900 0    50   Input ~ 0
DQ11_MB
Text GLabel 5300 2900 2    50   Input ~ 0
DQ11_DIMM
Wire Wire Line
	5200 3000 5300 3000
Text GLabel 5200 3000 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 3000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 3100 5300 3100
Text GLabel 5200 3100 0    50   Input ~ 0
DQ21_MB
Text GLabel 5300 3100 2    50   Input ~ 0
DQ21_DIMM
Wire Wire Line
	5200 3200 5300 3200
Text GLabel 5200 3200 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 3200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 3300 5300 3300
Text GLabel 5200 3300 0    50   Input ~ 0
DQ17_MB
Text GLabel 5300 3300 2    50   Input ~ 0
DQ17_DIMM
Wire Wire Line
	5200 3400 5300 3400
Text GLabel 5200 3400 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 3400 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 3500 5300 3500
Text GLabel 5200 3500 0    50   Input ~ 0
DQS2_c_MB
Text GLabel 5300 3500 2    50   Input ~ 0
DQS2_c_DIMM
Wire Wire Line
	5200 3600 5300 3600
Text GLabel 5200 3600 0    50   Input ~ 0
DQS2_t_MB
Text GLabel 5300 3600 2    50   Input ~ 0
DQS2_t_DIMM
Wire Wire Line
	5200 3700 5300 3700
Text GLabel 5200 3700 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 3700 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 3800 5300 3800
Text GLabel 5200 3800 0    50   Input ~ 0
DQ23_MB
Text GLabel 5300 3800 2    50   Input ~ 0
DQ23_DIMM
Wire Wire Line
	5200 3900 5300 3900
Text GLabel 5200 3900 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 3900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 4000 5300 4000
Text GLabel 5200 4000 0    50   Input ~ 0
DQ19_MB
Text GLabel 5300 4000 2    50   Input ~ 0
DQ19_DIMM
Wire Wire Line
	5200 4100 5300 4100
Text GLabel 5200 4100 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 4100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 4200 5300 4200
Text GLabel 5200 4200 0    50   Input ~ 0
DQ29_MB
Text GLabel 5300 4200 2    50   Input ~ 0
DQ29_DIMM
Wire Wire Line
	5200 4300 5300 4300
Text GLabel 5200 4300 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 4300 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 4400 5300 4400
Text GLabel 5200 4400 0    50   Input ~ 0
DQ25_MB
Text GLabel 5300 4400 2    50   Input ~ 0
DQ25_DIMM
Wire Wire Line
	5200 4500 5300 4500
Text GLabel 5200 4500 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 4500 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 4600 5300 4600
Text GLabel 5200 4600 0    50   Input ~ 0
DQS3_c_MB
Text GLabel 5300 4600 2    50   Input ~ 0
DQS3_c_DIMM
Wire Wire Line
	5200 4700 5300 4700
Text GLabel 5200 4700 0    50   Input ~ 0
DQS3_t_MB
Text GLabel 5300 4700 2    50   Input ~ 0
DQS3_t_DIMM
Wire Wire Line
	5200 4800 5300 4800
Text GLabel 5200 4800 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 4800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 4900 5300 4900
Text GLabel 5200 4900 0    50   Input ~ 0
DQ31_MB
Text GLabel 5300 4900 2    50   Input ~ 0
DQ31_DIMM
Wire Wire Line
	5200 5000 5300 5000
Text GLabel 5200 5000 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 5000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 5100 5300 5100
Text GLabel 5200 5100 0    50   Input ~ 0
DQ27_MB
Text GLabel 5300 5100 2    50   Input ~ 0
DQ27_DIMM
Wire Wire Line
	5200 5200 5300 5200
Text GLabel 5200 5200 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 5200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 5300 5300 5300
Text GLabel 5200 5300 0    50   Input ~ 0
CB5_MB
Text GLabel 5300 5300 2    50   Input ~ 0
CB5_DIMM
Wire Wire Line
	5200 5400 5300 5400
Text GLabel 5200 5400 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 5400 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 5500 5300 5500
Text GLabel 5200 5500 0    50   Input ~ 0
CB1_MB
Text GLabel 5300 5500 2    50   Input ~ 0
CB1_DIMM
Wire Wire Line
	5200 5600 5300 5600
Text GLabel 5200 5600 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 5600 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 5700 5300 5700
Text GLabel 5200 5700 0    50   Input ~ 0
DQS8_c_MB
Text GLabel 5300 5700 2    50   Input ~ 0
DQS8_c_DIMM
Wire Wire Line
	5200 5800 5300 5800
Text GLabel 5200 5800 0    50   Input ~ 0
DQS8_t_MB
Text GLabel 5300 5800 2    50   Input ~ 0
DQS8_t_DIMM
Wire Wire Line
	5200 5900 5300 5900
Text GLabel 5200 5900 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 5900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 6000 5300 6000
Text GLabel 5200 6000 0    50   Input ~ 0
CB7_MB
Text GLabel 5300 6000 2    50   Input ~ 0
CB7_DIMM
Wire Wire Line
	5200 6100 5300 6100
Text GLabel 5200 6100 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 6100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 6200 5300 6200
Text GLabel 5200 6200 0    50   Input ~ 0
CB3_MB
Text GLabel 5300 6200 2    50   Input ~ 0
CB3_DIMM
Wire Wire Line
	5200 6300 5300 6300
Text GLabel 5200 6300 0    50   Input ~ 0
VSS_MB
Text GLabel 5300 6300 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	5200 6400 5300 6400
Text GLabel 5200 6400 0    50   Input ~ 0
CKE1_NC_MB
Text GLabel 5300 6400 2    50   Input ~ 0
CKE1_NC_DIMM
Wire Wire Line
	5200 6500 5300 6500
Text GLabel 5200 6500 0    50   Input ~ 0
VDD_MB
Text GLabel 5300 6500 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	5200 6600 5300 6600
Text GLabel 5200 6600 0    50   Input ~ 0
NC_MB
Text GLabel 5300 6600 2    50   Input ~ 0
NC_DIMM
Wire Wire Line
	5200 6700 5300 6700
Text GLabel 5200 6700 0    50   Input ~ 0
VDD_MB
Text GLabel 5300 6700 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	5200 6800 5300 6800
Text GLabel 5200 6800 0    50   Input ~ 0
BG1_MB
Text GLabel 5300 6800 2    50   Input ~ 0
BG1_DIMM
Text GLabel 5200 6900 0    50   Input ~ 0
ALERT_n_MB
Text GLabel 5300 6900 2    50   Input ~ 0
ALERT_n_DIMM
Wire Wire Line
	5200 7000 5300 7000
Text GLabel 5200 7000 0    50   Input ~ 0
VDD_MB
Text GLabel 5300 7000 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	5200 7100 5300 7100
Text GLabel 5200 7100 0    50   Input ~ 0
A11_MB
Text GLabel 5300 7100 2    50   Input ~ 0
A11_DIMM
Wire Wire Line
	5200 7200 5300 7200
Text GLabel 5200 7200 0    50   Input ~ 0
A7_MB
Text GLabel 5300 7200 2    50   Input ~ 0
A7_DIMM
Wire Wire Line
	5200 7300 5300 7300
Text GLabel 5200 7300 0    50   Input ~ 0
VDD_MB
Text GLabel 5300 7300 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	5200 7400 5300 7400
Text GLabel 5200 7400 0    50   Input ~ 0
A5_MB
Text GLabel 5300 7400 2    50   Input ~ 0
A5_DIMM
Wire Wire Line
	5200 7500 5300 7500
Text GLabel 5200 7500 0    50   Input ~ 0
A4_MB
Text GLabel 5300 7500 2    50   Input ~ 0
A4_DIMM
Wire Wire Line
	5200 7600 5300 7600
Text GLabel 5200 7600 0    50   Input ~ 0
VDD_MB
Text GLabel 5300 7600 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	5200 7700 5300 7700
Text GLabel 5200 7700 0    50   Input ~ 0
A2_MB
Text GLabel 5300 7700 2    50   Input ~ 0
A2_DIMM
Wire Wire Line
	6800 600  6900 600 
Text GLabel 6800 600  0    50   Input ~ 0
VDD_MB
Text GLabel 6900 600  2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	6800 700  6900 700 
Text GLabel 6800 700  0    50   Input ~ 0
CK1_t_MB
Text GLabel 6900 700  2    50   Input ~ 0
CK1_t_DIMM
Wire Wire Line
	6800 800  6900 800 
Text GLabel 6800 800  0    50   Input ~ 0
CK1_c_MB
Text GLabel 6900 800  2    50   Input ~ 0
CK1_c_DIMM
Wire Wire Line
	6800 900  6900 900 
Text GLabel 6800 900  0    50   Input ~ 0
VDD_MB
Text GLabel 6900 900  2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	6800 1000 6900 1000
Text GLabel 6800 1000 0    50   Input ~ 0
VTT_MB
Text GLabel 6900 1000 2    50   Input ~ 0
VTT_DIMM
Wire Wire Line
	6800 1100 6900 1100
Text GLabel 6800 1100 0    50   Input ~ 0
PARITY_MB
Text GLabel 6900 1100 2    50   Input ~ 0
PARITY_DIMM
Wire Wire Line
	6800 1200 6900 1200
Text GLabel 6800 1200 0    50   Input ~ 0
VDD_MB
Text GLabel 6900 1200 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	6800 1300 6900 1300
Text GLabel 6800 1300 0    50   Input ~ 0
BA1_MB
Text GLabel 6900 1300 2    50   Input ~ 0
BA1_DIMM
Wire Wire Line
	6800 1400 6900 1400
Text GLabel 6800 1400 0    50   Input ~ 0
A10_AP_MB
Text GLabel 6900 1400 2    50   Input ~ 0
A10_AP_DIMM
Wire Wire Line
	6800 1500 6900 1500
Text GLabel 6800 1500 0    50   Input ~ 0
VDD_MB
Text GLabel 6900 1500 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	6800 1600 6900 1600
Text GLabel 6800 1600 0    50   Input ~ 0
NC_MB
Text GLabel 6900 1600 2    50   Input ~ 0
NC_DIMM
Text GLabel 6800 1700 0    50   Input ~ 0
WE_n_A14_MB
Text GLabel 6900 1700 2    50   Input ~ 0
WE_n_A14_DIMM
Wire Wire Line
	6800 1800 6900 1800
Text GLabel 6800 1800 0    50   Input ~ 0
VDD_MB
Text GLabel 6900 1800 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	6800 1900 6900 1900
Text GLabel 6800 1900 0    50   Input ~ 0
NC_MB
Text GLabel 6900 1900 2    50   Input ~ 0
NC_DIMM
Wire Wire Line
	6800 2000 6900 2000
Text GLabel 6800 2000 0    50   Input ~ 0
VDD_MB
Text GLabel 6900 2000 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	6800 2100 6900 2100
Text GLabel 6800 2100 0    50   Input ~ 0
A13_MB
Text GLabel 6900 2100 2    50   Input ~ 0
A13_DIMM
Wire Wire Line
	6800 2200 6900 2200
Text GLabel 6800 2200 0    50   Input ~ 0
VDD_MB
Text GLabel 6900 2200 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	6800 2300 6900 2300
Text GLabel 6800 2300 0    50   Input ~ 0
A17_MB
Text GLabel 6900 2300 2    50   Input ~ 0
A17_DIMM
Wire Wire Line
	6800 2400 6900 2400
Text GLabel 6800 2400 0    50   Input ~ 0
NC_C2_MB
Text GLabel 6900 2400 2    50   Input ~ 0
NC_C2_DIMM
Wire Wire Line
	6800 2500 6900 2500
Text GLabel 6800 2500 0    50   Input ~ 0
VDD_MB
Text GLabel 6900 2500 2    50   Input ~ 0
VDD_DIMM
Wire Wire Line
	6800 2600 6900 2600
Text GLabel 6800 2600 0    50   Input ~ 0
CS3_n_C1,NC_MB
Text GLabel 6900 2600 2    50   Input ~ 0
CS3_n_C1,NC_DIMM
Wire Wire Line
	6800 2700 6900 2700
Text GLabel 6800 2700 0    50   Input ~ 0
SA2_MB
Text GLabel 6900 2700 2    50   Input ~ 0
SA2_DIMM
Wire Wire Line
	6800 2800 6900 2800
Text GLabel 6800 2800 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 2800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 2900 6900 2900
Text GLabel 6800 2900 0    50   Input ~ 0
DQ37_MB
Text GLabel 6900 2900 2    50   Input ~ 0
DQ37_DIMM
Wire Wire Line
	6800 3000 6900 3000
Text GLabel 6800 3000 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 3000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 3100 6900 3100
Text GLabel 6800 3100 0    50   Input ~ 0
DQ33_MB
Text GLabel 6900 3100 2    50   Input ~ 0
DQ33_DIMM
Wire Wire Line
	6800 3200 6900 3200
Text GLabel 6800 3200 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 3200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 3300 6900 3300
Text GLabel 6800 3300 0    50   Input ~ 0
DQS4_c_MB
Text GLabel 6900 3300 2    50   Input ~ 0
DQS4_c_DIMM
Wire Wire Line
	6800 3400 6900 3400
Text GLabel 6800 3400 0    50   Input ~ 0
DQS4_t_MB
Text GLabel 6900 3400 2    50   Input ~ 0
DQS4_t_DIMM
Wire Wire Line
	6800 3500 6900 3500
Text GLabel 6800 3500 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 3500 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 3600 6900 3600
Text GLabel 6800 3600 0    50   Input ~ 0
DQ39_MB
Text GLabel 6900 3600 2    50   Input ~ 0
DQ39_DIMM
Wire Wire Line
	6800 3700 6900 3700
Text GLabel 6800 3700 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 3700 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 3800 6900 3800
Text GLabel 6800 3800 0    50   Input ~ 0
DQ35_MB
Text GLabel 6900 3800 2    50   Input ~ 0
DQ35_DIMM
Wire Wire Line
	6800 3900 6900 3900
Text GLabel 6800 3900 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 3900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 4000 6900 4000
Text GLabel 6800 4000 0    50   Input ~ 0
DQ45_MB
Text GLabel 6900 4000 2    50   Input ~ 0
DQ45_DIMM
Wire Wire Line
	6800 4100 6900 4100
Text GLabel 6800 4100 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 4100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 4200 6900 4200
Text GLabel 6800 4200 0    50   Input ~ 0
DQ41_MB
Text GLabel 6900 4200 2    50   Input ~ 0
DQ41_DIMM
Wire Wire Line
	6800 4300 6900 4300
Text GLabel 6800 4300 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 4300 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 4400 6900 4400
Text GLabel 6800 4400 0    50   Input ~ 0
DQS5_c_MB
Text GLabel 6900 4400 2    50   Input ~ 0
DQS5_c_DIMM
Wire Wire Line
	6800 4500 6900 4500
Text GLabel 6800 4500 0    50   Input ~ 0
DQS5_t_MB
Text GLabel 6900 4500 2    50   Input ~ 0
DQS5_t_DIMM
Wire Wire Line
	6800 4600 6900 4600
Text GLabel 6800 4600 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 4600 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 4700 6900 4700
Text GLabel 6800 4700 0    50   Input ~ 0
DQ47_MB
Text GLabel 6900 4700 2    50   Input ~ 0
DQ47_DIMM
Wire Wire Line
	6800 4800 6900 4800
Text GLabel 6800 4800 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 4800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 4900 6900 4900
Text GLabel 6800 4900 0    50   Input ~ 0
DQ43_MB
Text GLabel 6900 4900 2    50   Input ~ 0
DQ43_DIMM
Wire Wire Line
	6800 5000 6900 5000
Text GLabel 6800 5000 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 5000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 5100 6900 5100
Text GLabel 6800 5100 0    50   Input ~ 0
DQ53_MB
Text GLabel 6900 5100 2    50   Input ~ 0
DQ53_DIMM
Wire Wire Line
	6800 5200 6900 5200
Text GLabel 6800 5200 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 5200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 5300 6900 5300
Text GLabel 6800 5300 0    50   Input ~ 0
DQ49_MB
Text GLabel 6900 5300 2    50   Input ~ 0
DQ49_DIMM
Wire Wire Line
	6800 5400 6900 5400
Text GLabel 6800 5400 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 5400 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 5500 6900 5500
Text GLabel 6800 5500 0    50   Input ~ 0
DQS6_c_MB
Text GLabel 6900 5500 2    50   Input ~ 0
DQS6_c_DIMM
Wire Wire Line
	6800 5600 6900 5600
Text GLabel 6800 5600 0    50   Input ~ 0
DQS6_t_MB
Text GLabel 6900 5600 2    50   Input ~ 0
DQS6_t_DIMM
Wire Wire Line
	6800 5700 6900 5700
Text GLabel 6800 5700 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 5700 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 5800 6900 5800
Text GLabel 6800 5800 0    50   Input ~ 0
DQ55_MB
Text GLabel 6900 5800 2    50   Input ~ 0
DQ55_DIMM
Wire Wire Line
	6800 5900 6900 5900
Text GLabel 6800 5900 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 5900 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 6000 6900 6000
Text GLabel 6800 6000 0    50   Input ~ 0
DQ51_MB
Text GLabel 6900 6000 2    50   Input ~ 0
DQ51_DIMM
Wire Wire Line
	6800 6100 6900 6100
Text GLabel 6800 6100 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 6100 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 6200 6900 6200
Text GLabel 6800 6200 0    50   Input ~ 0
DQ61_MB
Text GLabel 6900 6200 2    50   Input ~ 0
DQ61_DIMM
Wire Wire Line
	6800 6300 6900 6300
Text GLabel 6800 6300 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 6300 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 6400 6900 6400
Text GLabel 6800 6400 0    50   Input ~ 0
DQ57_MB
Text GLabel 6900 6400 2    50   Input ~ 0
DQ57_DIMM
Wire Wire Line
	6800 6500 6900 6500
Text GLabel 6800 6500 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 6500 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 6600 6900 6600
Text GLabel 6800 6600 0    50   Input ~ 0
DQS7_c_MB
Text GLabel 6900 6600 2    50   Input ~ 0
DQS7_c_DIMM
Wire Wire Line
	6800 6700 6900 6700
Text GLabel 6800 6700 0    50   Input ~ 0
DQS7_t_MB
Text GLabel 6900 6700 2    50   Input ~ 0
DQS7_t_DIMM
Wire Wire Line
	6800 6800 6900 6800
Text GLabel 6800 6800 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 6800 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 6900 6900 6900
Text GLabel 6800 6900 0    50   Input ~ 0
DQ63_MB
Text GLabel 6900 6900 2    50   Input ~ 0
DQ63_DIMM
Wire Wire Line
	6800 7000 6900 7000
Text GLabel 6800 7000 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 7000 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 7100 6900 7100
Text GLabel 6800 7100 0    50   Input ~ 0
DQ59_MB
Text GLabel 6900 7100 2    50   Input ~ 0
DQ59_DIMM
Wire Wire Line
	6800 7200 6900 7200
Text GLabel 6800 7200 0    50   Input ~ 0
VSS_MB
Text GLabel 6900 7200 2    50   Input ~ 0
VSS_DIMM
Wire Wire Line
	6800 7300 6900 7300
Text GLabel 6800 7300 0    50   Input ~ 0
VDDSPD_MB
Text GLabel 6900 7300 2    50   Input ~ 0
VDDSPD_DIMM
Wire Wire Line
	6800 7400 6900 7400
Text GLabel 6800 7400 0    50   Input ~ 0
SDA_MB
Text GLabel 6900 7400 2    50   Input ~ 0
SDA_DIMM
Wire Wire Line
	6800 7500 6900 7500
Text GLabel 6800 7500 0    50   Input ~ 0
VPP_MB
Text GLabel 6900 7500 2    50   Input ~ 0
VPP_DIMM
Wire Wire Line
	6800 7600 6900 7600
Text GLabel 6800 7600 0    50   Input ~ 0
VPP_MB
Text GLabel 6900 7600 2    50   Input ~ 0
VPP_DIMM
Wire Wire Line
	6800 7700 6900 7700
Text GLabel 6800 7700 0    50   Input ~ 0
VPP_MB
Text GLabel 6900 7700 2    50   Input ~ 0
VPP_DIMM
$EndSCHEMATC
